png(file="E:/Coursera/RWorkDir/EDA1/plot3.png")
HP<-read.table(file="E:/Coursera/RWorkDir/Power/HPC.txt",sep=";",skip=66637,nrows=2880,col.names=colnames(read.table("E:/Coursera/RWorkDir/Power/HPC.txt",nrow=1,header=TRUE,sep=";")))
HP$Date1<-paste(HP$Date,HP$Time)
HP$Date1<-strptime(HP$Date1,"%d/%m/%Y %H:%M:%S")
HPN<-HP[,c(3,4,5,6,7,8,9,10)]
library(datasets)
par(bg="transparent")
with(HPN,plot(Date1,Sub_metering_1,type="s",xlab="",ylab="Energy sub metering"))
lines(HPN$Date1,HPN$Sub_metering_2,type="s",col="red")
lines(HPN$Date1,HPN$Sub_metering_3,type="s",col="blue")
Sub<-c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
colors<-c("black","red","blue")
legend("topright",Sub,col=colors,lty=1,lwd=2,bty="1")
dev.off()
